name = "gmailaccounts"

main = "src/index.js"

compatibility_date = "2026-09-25"

compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB1"
database_name = "gmail-db"
database_id = "8b16ac40-600f-45c5-9b3e-4a2cdff646a6"

[observability]
enabled = true
